package com.paymybuddy.paymybuddy.user.ui;

import java.util.UUID;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import com.paymybuddy.paymybuddy.user.service.UserRegistrationService;
import com.paymybuddy.paymybuddy.utils.MainLogger;

import jakarta.validation.Valid;

@Controller
public class UserRegistrationController {

    private static final MainLogger logger = MainLogger.getLogger(UserRegistrationController.class);

    private final UserRegistrationService userRegistrationService;

    public UserRegistrationController(UserRegistrationService userRegistrationService) {
        this.userRegistrationService = userRegistrationService;
    }

    @GetMapping("/register")
    public String displayUserRegistrationForm(Model model) {
        final String autogeneratedPassword = UUID.randomUUID().toString();
        logger.info("Getting the registration form");
        final UserRegistrationForm userRegistrationForm = new UserRegistrationForm(autogeneratedPassword, autogeneratedPassword);
        model.addAttribute("user", userRegistrationForm);
        return "user_registration";
    }

    @PostMapping("/register")
    public String handleUserForm(@Valid @ModelAttribute("user") UserRegistrationForm userRegistrationForm, Model model) {
        logger.info("Posting the filled form");
        model.addAttribute("userEmail", userRegistrationForm.getEmail());
        userRegistrationService.createAccount(userRegistrationForm.getEmail(), userRegistrationForm.getPassword());
        return "redirect:/login";
    }

}
