CREATE SCHEMA IF NOT EXISTS testdb;

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
    email    VARCHAR(125) NOT NULL PRIMARY KEY,
    username VARCHAR(50)  NOT NULL UNIQUE,
    password VARCHAR(150) NOT NULL
);

DROP TABLE IF EXISTS FRIENDS;
CREATE TABLE FRIENDS
(
    user_email VARCHAR(125) NOT NULL,
    friends    VARCHAR(50)  NOT NULL
);

DROP TABLE IF EXISTS ACCOUNTS;
CREATE TABLE ACCOUNTS
(
    id      INT AUTO_INCREMENT PRIMARY KEY,
    balance FLOAT,
    RIB     VARCHAR(125) UNIQUE,
    user_id VARCHAR(125) NOT NULL
);

DROP TABLE IF EXISTS TRANSACTIONS;
CREATE TABLE TRANSACTIONS
(
    id       INT AUTO_INCREMENT PRIMARY KEY,
    amount   FLOAT,
    type     VARCHAR(125) NOT NULL,
    SENDER   VARCHAR(125),
    RECEIVER VARCHAR(125),
    DATE     TIMESTAMP    NOT NULL,
    DESCRIPTION VARCHAR(255)
);